# Default values for drr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  image:
    repository: harbor.sheldan.dev/drr
    pullPolicy: IfNotPresent
    image: drr-backend
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.0.1
  debug:
    enabled: true
    port: 5005
  service:
    type: ClusterIP
    port: 8080
    name: backend-service
  nodeSelector: {}

  tolerations: []

  affinity: {}

  resources:

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  ingress:
    enabled: false
    annotations: {}
    labels: {}
    path: /

    pathType: Prefix

    hosts:
    extraPaths: []
    tls: []

  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 5
    failureThreshold: 3

frontend:
  image:
    repository: harbor.sheldan.dev/drr
    pullPolicy: IfNotPresent
    image: drr-frontend
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.0.1
  port: 8080
  service:
    type: ClusterIP
    port: 8080
    name: frontend
  nodeSelector: {}
  livenessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3

  tolerations: []

  affinity: {}

  resources:

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  ingress:
    enabled: false
    annotations: {}
    labels: {}
    path: /

    pathType: Prefix

    hosts:
    extraPaths: []
    tls: []

  replicaCount: 1

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


